trigger:
  branches:
      include:
      - yaml-changes

steps:
- task: UseNode@1
  displayName: 'Use Node.js 16.15.0'
  inputs:
    version: '16.15.0'

- bash: 
    npm install sfdx-cli --global
  displayName: Install Salesforce CLI

- task: DownloadSecureFile@1
  name: jwtKey
  displayName: 'Download Server JWT Key'
  inputs:
    secureFile: 'server.key'
- bash:
    sfdx config:set restDeploy=false --global
  displayName: Use SOAP API for Deployment
- bash: 
    sfdx force:auth:jwt:grant --clientid 3MVG9fe4g9fhX0E59uOvlF3zPUG8jQOs7wCl7iZ.oidpWiyVAFXlCjsvCdw7wsX4Sar4SHmUQOwu6AG3SmrQo --jwtkeyfile $(jwtKey.secureFilePath) --username sfcicid@yahoo.com --instanceurl https://login.salesforce.com -a DRish
  displayName: Authorize salesforce org
- bash:
    ls -al && echo 'this is PWD' && pwd
  displayName: List Files on Pool

- bash:
    sfdx force:source:deploy -l RunLocalTests -c -x manifest/package.xml -u sfcicid@yahoo.com -w 10
  displayName: Run Validation on source code

- bash: 
    sfdx force:source:deploy -p force-app -w 10 -u sfcicid@yahoo.com
  displayName: Deploy source code to Salesforce Org.
